### PR TITLE
Add basic proxy support

### PR DESCRIPTION
**Pull request by drhey**
## Pull Request Checklist

**Is this in reference to an existing issue?**

- Yes. It's in reference to at least 3 requests for proxy support (mine included). Although, I am not sure if the others require proxy username and password support - it would be trivial for me to add, but I cannot validate as I don't require that functionality at the moment.

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [X] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

- Add ability to use a this plugin behind a proxy

### CODE REVIEW

**Comment by drhey** [comment]
Want to do just a little bit more testing.

**Comment by drhey** [comment]
My testing confirmed my changes are correct.

**Comment by majormoses** [comment]
forgot to request a CHANGELOG entry so I will do it.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-statuspage/versions/1.1.0

**Pull request merged**
