### PR TITLE
Allow desired component/incident status configuration per check.

### PR DESCRIPTION
**Pull request by athal7**
Some users may want to choose what the incident or component status is
for warning vs critical on a per-check basis, rather than having it
always be `major_outage` and `investigating`. This change provides that
capability, allows for ignoring of certain cases, and ensures only valid
statuses get sent to the statuspage api.

### CODE REVIEW

**Comment by athal7** [comment]
@eheydrick not sure if you're the right person to ping about this, but I saw that you have recent commits. Let me know if you have any thoughts!

**Comment by eheydrick** [comment]
Hey @athal7, thanks for the PR. It looks good. Are these changes backwards compatible?

**Comment by athal7** [comment]
@eheydrick there are a few minor changes that I thought made a bit more sense but happy to revert those if you think it makes more sense to keep them as they were:

### existing
#### component statuses
warning -> major outage
critical -> major outage

#### incident statuses
warning -> investigating
critical -> investigating

### new
#### component statuses
warning -> partial outage
critical -> major outage

#### incident statuses
warning -> identified
critical -> identified

**Comment by eheydrick** [comment]
That's actually OK since we're going to release a new major version anyways to remove Ruby 1.9.3 support. Could you add a blurb to the CHANGELOG about any issues/changes someone would face moving from the existing version.

**Comment by athal7** [comment]
@eheydrick how's that?

**Comment by eheydrick** [comment]
👍 Thanks!

**Comment by athal7** [comment]
Thank you!

**Comment by eheydrick** [comment]
These changes are in [1.0.0](https://rubygems.org/gems/sensu-plugins-statuspage/versions/1.0.0), now live on rubygems.

**Pull request merged**
