### PR TITLE
Add status rollup check

### PR DESCRIPTION
**Pull request by spacepants**
This adds a new check for the status rollup of a StatusPage instance.

## Pull Request Checklist

**Is this in reference to an existing issue?**
Nope.

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass 

#### New Plugins

- [ ] Tests

- [x] Add the plugin to the README

- [x] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose
Adds a new plugin to check the status rollup of a StatusPage instance.

#### Known Compatibility Issues
None.

### CODE REVIEW

**Comment by majormoses** [comment]
@spacepants this looks great, thanks for the contribution. I need a testing artifact, while automated is prefered I will take anything demonstrating input and output in a gist, screenshot, etc

**Comment by spacepants** [comment]
I tried to find some examples of automated tests for other sensu plugins, but I didn't have much luck. Got a link to one I can take a look at?

Here's a screenshot that shows its basic functionality.
screenshot

**Comment by majormoses** [comment]
The aws and mesos ones have some decent testing. We are gonna hopefully come up with our standard framework probably using test kitchen at some point. Let me know if you want to work on an automated test more if not I am more than happy to accept this as a testing artifact right now (might not always be the case).

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-statuspage/versions/1.2.0

**Pull request merged**
